version: '3'

services:
  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/var/www/html
    depends_on:
      - php
      - mysql

  # PHP service
  php:
    image: php:7.4-fpm
    volumes:
      - ./nginx/html:/var/www/html
    depends_on:
      - mysql

  # MySQL service
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./scripts/.config/my.cnf:/etc/my.cnf

  # WordPress service
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
